services:
  # webserver:
  #   image: unit:1.32.1-php8.2
  #   env_file:
  #     - .env.nginx
  #   volumes:
  #     - ./docker/unit.json:/docker-entrypoint.d/lumen.json
  #     - ./:/app/
  #   ports:
  #     - "9000:9000"
  #     - "80:80"
  db:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql
  cache:
    image: redis:7.4.0
    ports:
      - 6379:6379
