services:
  nginx:
    build: nginx:1.27.0-alpine
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./images/php/app/public:/var/www/html/app/public
      - /etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql
  cache:
    image: redis:7.4.0
    ports:
      - 6379:6379
